1. Tabelka z danymi jest tutaj: http://sqlfiddle.com/#!9/fe28ad/1

2. Skrypt do stworzenia bazy online od nowa z danymi testowymi:

CREATE TABLE TRADE (
    COUNTERPARTY_ID int(3),
    COUNTERPARTY_SOURCE int(3),
    SAP_FUNCTIONAL_AREA VARCHAR(10),
    GAAP_CODE VARCHAR(10)
);
INSERT INTO TRADE VALUES(1,1,"A11-1",NULL);
INSERT INTO TRADE VALUES(1,1,"A11-2",NULL);
INSERT INTO TRADE VALUES(1,1,"A11-3",NULL);


INSERT INTO TRADE VALUES(1,2,"A12-1",NULL);
INSERT INTO TRADE VALUES(1,2,"A12-2",NULL);

INSERT INTO TRADE VALUES(1,3,"A13-1",NULL);
INSERT INTO TRADE VALUES(1,3,"A13-2",NULL);

INSERT INTO TRADE VALUES(2,1,"A21-1",NULL);
INSERT INTO TRADE VALUES(2,1,"A21-2",NULL);
INSERT INTO TRADE VALUES(2,1,"A21-3",NULL);

INSERT INTO TRADE VALUES(2,2,"A22-1",NULL);
INSERT INTO TRADE VALUES(2,2,"A22-2",NULL);
INSERT INTO TRADE VALUES(2,2,"A22-3",NULL);

INSERT INTO TRADE VALUES(1,1,"AR",NULL);
INSERT INTO TRADE VALUES(2,2,"AR",NULL);

3. Rozwiązanie
SELECT COUNTERPARTY_ID,COUNTERPARTY_SOURCE 
from trade 
where (COUNTERPARTY_ID,COUNTERPARTY_SOURCE) not in (select COUNTERPARTY_ID,COUNTERPARTY_SOURCE 
from trade where SAP_FUNCTIONAL_AREA = 'AR')
group by COUNTERPARTY_ID,COUNTERPARTY_SOURCE  
